/**
 * Session Summary PDF generation for Share and Email.
 * Produces a single-page PDF artifact with session data.
 */

import { jsPDF } from 'jspdf';
import type { Session, SessionStats, User } from '../types';
import { formatTime } from './storage';

/** Derive recovery points (6–15) from coherence and stability. Non-competitive, represents nervous system recovery capacity. */
export function deriveRecoveryPoints(coherencePercent: number, stability: string): number {
  const stabilityScore = stability === 'High' ? 4 : stability === 'Medium' ? 2 : 0;
  const coherenceTier = coherencePercent >= 70 ? 5 : coherencePercent >= 50 ? 3 : coherencePercent >= 30 ? 2 : 1;
  const raw = 6 + stabilityScore + coherenceTier;
  return Math.min(15, Math.max(6, raw));
}

export interface SummaryPdfOptions {
  session: Session;
  stats: SessionStats;
  user: User;
  journeyName: string;
  peakCoherence: number;
  stability: string;
  /** Optional; show "—" if not available */
  avgHeartRate?: number | null;
  /** Optional; show "—" if not available */
  avgHRV?: number | null;
}

/**
 * Generate a single-page PDF with session summary data.
 * Includes: sessionName, coherenceScore, sessionDuration, sessionTime, avgHeartRate, avgHRV, recoveryPoints.
 */
export async function generateSummaryPdfBlob(options: SummaryPdfOptions): Promise<Blob> {
  const {
    session,
    stats,
    user,
    journeyName,
    peakCoherence,
    stability,
    avgHeartRate,
    avgHRV,
  } = options;

  const recoveryPoints = deriveRecoveryPoints(stats.coherencePercent, stability);
  const sessionTime = new Date(session.startTime).toLocaleString();
  const durationStr = `${formatTime(session.duration)} min`;
  const coherenceScore = Math.round(stats.coherencePercent);
  const peakPct = Math.round(peakCoherence * 100);

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Title
  doc.setFontSize(22);
  doc.setTextColor(79, 168, 122); // champagne/gold-ish from spec
  doc.text('SoundBed Session Summary', pageWidth / 2, y, { align: 'center' });
  y += 14;

  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text(`${user.name} · ${sessionTime}`, pageWidth / 2, y, { align: 'center' });
  y += 20;

  // Session name (journey)
  doc.setFontSize(16);
  doc.setTextColor(50, 50, 50);
  doc.text(journeyName, margin, y);
  y += 10;

  // Key metrics
  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  const metrics = [
    ['Coherence score', `${coherenceScore}%`],
    ['Peak coherence', `${peakPct}%`],
    ['Duration', durationStr],
    ['Session time', sessionTime],
    ['Avg. heart rate', avgHeartRate != null ? `${Math.round(avgHeartRate)} bpm` : '—'],
    ['Avg. HRV', avgHRV != null ? `${Math.round(avgHRV)} ms` : '—'],
    ['Recovery points', String(recoveryPoints)],
  ];
  const fontName = doc.getFont().fontName;
  metrics.forEach(([label, value]) => {
    doc.text(label + ': ', margin, y);
    doc.setFont(fontName, 'bold');
    doc.text(value, margin + doc.getTextWidth(label + ': ') + 2, y);
    doc.setFont(fontName, 'normal');
    y += 8;
  });

  y += 10;
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by SoundBed · Your body remembers. Small shifts compound.', pageWidth / 2, y, { align: 'center' });

  const blob = doc.output('blob');
  return blob;
}
